# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rspec_outlines}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["George Ogata"]
  s.date = %q{2009-09-14}
  s.description = %q{TODO: longer description of your gem}
  s.email = %q{george.ogata@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/rspec_outlines.rb",
     "lib/rspec_outlines/error.rb",
     "lib/rspec_outlines/example_group.rb",
     "lib/rspec_outlines/example_methods.rb",
     "lib/rspec_outlines/example_proxy.rb",
     "lib/rspec_outlines/outline.rb",
     "rspec_outlines.gemspec",
     "spec/example_group_spec.rb",
     "spec/example_methods_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec_integration/integration_spec.rb",
     "spec_integration/spec.opts",
     "spec_integration/spec_files/should_not_affect_normal_specs.rb",
     "spec_integration/spec_files/should_run_the_outline_for_each_set_of_values_given.rb"
  ]
  s.homepage = %q{http://github.com/oggy/rspec_outlines}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{TODO: one-line summary of your gem}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/example_methods_spec.rb",
     "spec/example_group_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<mocha>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<mocha>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<mocha>, [">= 0"])
  end
end
